# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7ae17b7d36bf3934f95f4751e5b1af968663d9e0d77cbb139c04d21b2aebabb66b83e55c63da89e38752ba0a5ccf9fb4df66e94937f380fe319963a7a5311a1

test:
  secret_key_base: 44ce2b3178dfbad3507b781c56d791d3b8643afb43d36c8d4fb46433d618a82f93331bf67cf6498e2a8ba712f2bfcd3b1de28bbd2f581c37cf70e105dbf68554

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
